### ISSUE TITLE
Milestone for Progress 2

### ISSUE THREAD

**Issue by Raikirieiei** [Raikirieiei/Project-Oruzhiye#15]
- [x] Basic movement and fix bug
- [x] 3 map including boss
- [x] UI
- [x] Basic AI for mob
